[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"
[font]
size = 14
[font.normal]
family = "JetBrainsMono Nerd Font"
[shell]
program = "/opt/homebrew/bin/tmux"
[colors.primary]
background = "0x101010"
foreground = "0xEEEEEE"
