live_config_reload = true
[env]
TERM = "xterm-256color"
[font]
size = 15
offset = { x = 0, y = 0 }
[font.bold]
family = "FiraCode Nerd Font"
style = "Heavy"
[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Heavy Italic"
[font.italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"
[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"
[shell]
program = "/opt/homebrew/bin/tmux"
[colors.primary]
background = "0x101010"
foreground = "0xEEEEEE"
[window]
decorations = "buttonless"
dynamic_padding = false
[window.padding]
x = 25
y = 20
