live_config_reload = true
[env]
TERM = "xterm-256color"
[font]
size = 18
offset = { x = 0, y = 0 }
[font.bold]
family = "Inconsolata Nerd Font"
style = "Heavy"
[font.bold_italic]
family = "Inconsolata Nerd Font"
style = "Heavy Italic"
[font.italic]
family = "Inconsolata Nerd Font"
style = "Medium Italic"
[font.normal]
family = "Inconsolata Nerd Font"
[shell]
program = "/opt/homebrew/bin/tmux"
[window]
decorations = "buttonless"
[window.padding]
x = 15
y = 15
[colors.primary]
background = "0x000000"
