[shell]
program = '/opt/homebrew/bin/tmux'

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Noto Sans Mono"

[scrolling]
history = 0

[window]
dynamic_title = false
title = "Terminal"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

# Colors (GruvboxDarkHard)

[colors.bright]
black = '#928374'
blue = '#83a598'
cyan = '#8ec07c'
green = '#b8bb26'
magenta = '#d3869b'
red = '#fb4934'
white = '#ebdbb2'
yellow = '#fabd2f'

[colors.cursor]
cursor = '#ebdbb2'
text = '#1b1b1b'

[colors.normal]
black = '#1b1b1b'
blue = '#458588'
cyan = '#689d6a'
green = '#98971a'
magenta = '#b16286'
red = '#cc241d'
white = '#a89984'
yellow = '#d79921'

[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

[colors.selection]
background = '#665c54'
text = '#ebdbb2'
