[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"
[font]
size = 17
[font.normal]
family = "MesloLGS Nerd Font"
[shell]
program = "/opt/homebrew/bin/tmux"
[colors.primary]
background = "0x262626"
foreground = "0xEEEEEE"
