[shell]
program = '/opt/homebrew/bin/tmux'

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[scrolling]
history = 0

[window]
dynamic_title = false
title = "Terminal"
padding = { x = 5, y = 5 }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

# Colors (tokyonight)

[colors.bright]
black = '#414868'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
magenta = '#bb9af7'
red = '#f7768e'
white = '#c0caf5'
yellow = '#e0af68'

[colors.cursor]
cursor = '#c0caf5'
text = '#15161e'

[colors.normal]
black = '#15161e'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
magenta = '#bb9af7'
red = '#f7768e'
white = '#a9b1d6'
yellow = '#e0af68'

[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.selection]
background = '#33467c'
text = '#c0caf5'
