[shell]
program = '/opt/homebrew/bin/tmux'

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Noto Sans Mono"

[scrolling]
history = 0

[window]
dynamic_title = false
title = "Terminal"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

# Colors (rose-pine)

[colors.bright]
black = '#6e6a86'
blue = '#31748f'
cyan = '#ebbcba'
green = '#9ccfd8'
magenta = '#c4a7e7'
red = '#eb6f92'
white = '#e0def4'
yellow = '#f6c177'

[colors.cursor]
cursor = '#e0def4'
text = '#191724'

[colors.normal]
black = '#26233a'
blue = '#31748f'
cyan = '#ebbcba'
green = '#9ccfd8'
magenta = '#c4a7e7'
red = '#eb6f92'
white = '#e0def4'
yellow = '#f6c177'

[colors.primary]
background = '#191724'
foreground = '#e0def4'

[colors.selection]
background = '#191724'
text = '#e0def4'
